### ISSUE TITLE
Как правильно использовать локализацию?

### ISSUE THREAD

**Issue by bybelov** [Via-profit/js-form-validator#1]
Приветствую.
Пример из демки,
Если написать locale: 'ru', и затем в message передавать объект ru, то не работает. (Если ru заменить на en, то срабатывает)
Сообщение игнорируется и используется дефолтное из en объекта зашитого в скрипте js-form-validator.js
```
			case'demo-form-3':
				new Validator(form, function (err, res) {
					res && new JsSplash('Выполнено успешно', {
						closeBtn: false,
						autoClose: 1600
					});
				}, {
					locale: 'ru',
					messages: {
						ru : {
							milk: {
								incorrect: 'Это не Молоко ;-)'
							}
						}
					},
					rules: {
						milk: function (value) {
							return (value.trim().toLowerCase() === 'молоко');
						}
					}
				});
			break;
```
Как правильно использовать локализацию ?
Допустим есть полностью переведенный объект en из скрипта.
Спасибо. (может быть я что-то не так делаю...)

**Comment by Via-profit** [comment]
Вы все делаете правильно. Как оказалось, имеется ошибка в методе применения пользовательских настроек (**applySettings**) после комментария apply other settings. Т.о. ни одни пользовательские настройки не применялись.
Ниже исправленный фрагмент кода.
```javascript
// apply other settings
Object.keys(settings).forEach(function (param) {
    self.settings[param] = settings[param];
});

return this;
```
